# Generated by Django 6.0.4 on 2026-05-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_item_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.URLField(default='https://cdn-icons-png.flaticon.com/512/1147/1147856.png', max_length=1000),
        ),
    ]
